{% set name = "datetype" %}
{% set version = "2023.11.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datetype-{{ version }}.tar.gz
  sha256: e99e1355bab88a9f7a92f8c84a8c6997a7427e73df88e15faaa873df11519020

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.10

test:
  imports:
    - datetype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/glyph/DateType
  summary: A type wrapper for the standard library `datetime` that supplies stricter checks.
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
