{% set python_min = '3.10' %}
{% set name = "datetype" %}
{% set version = "2024.2.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datetype-{{ version }}.tar.gz
  sha256: 9840ab907099a4e0ecd9418464bc4b68d525dd0e588a35f9b9bec5a5cda27b69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - datetype
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/glyph/DateType
  summary: A type wrapper for the standard library `datetime` that supplies stricter checks.
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
